export const  categories =[
    {
        id:1,
        name:"Breakfast",
        urlParamName:"breakfast"
    },
    {
        id:2,
        name:"Burger",
        urlParamName:"burger"
    },
    {
        id:3,
        name:"Noodles",
        urlParamName:"noodles"
    },
    {
        id:4,
        name:"Sandwiches",
        urlParamName:"sandwiches"
    },
    {
        id:5,
        name:"Thali",
        urlParamName:"thali"
    },
    {
        id:6,
        name:"Wraps",
        urlParamName:"wraps"
    }

]